
fixed test_guilded_rose.py so it passed   (changed fixme to foo)